### ISSUE TITLE
[Art] Player Char Sprites

### ISSUE THREAD

**Issue by ErdrickBelmont** [ErdrickBelmont/Buddy_Jam_2024_Team_4#1]
- [x] Basic design
- [x] Standing sprites
  - [x] Side views
  - [x] Forwards
  - [x] Backwards
- [x] Walk cycle
  - [x] Side view
  - [x] Forwards
  - [x] Backwards
- [x] Swinging axe animation
- [ ] Hit slash

**Comment by vywn** [comment]
added standing sprites - https://github.com/ErdrickBelmont/Buddy_Jam_2024_Team_4/commit/e7986da61800ad122187ded873dcca253998216d

**Comment by vywn** [comment]
working on the animations, need to add the axe but got a walk cycle going

![player-right-walk](https://github.com/ErdrickBelmont/Buddy_Jam_2024_Team_4/assets/172531467/61db6dc1-1e76-4cfd-a7ad-f7342d1d496b)

**Comment by vywn** [comment]
walk animations added: [219d79e](https://github.com/ErdrickBelmont/Buddy_Jam_2024_Team_4/commit/219d79e8389e3b4ba05ff69b5450b07f089a10c6)
