### ISSUE TITLE
[Art] Background assets

### ISSUE THREAD

**Issue by ErdrickBelmont** [ErdrickBelmont/Buddy_Jam_2024_Team_4#2]
- [x] ground tiles
- [x] tree walls
- [ ] Doors to different parts of the dungeon

**Comment by vywn** [comment]
Not sure what "doors" we need if the areas are surrounded by walls and it's obvious where the entrance/exits are, but I guess I can make a glowing light or shadow tile or sth

---

Experimented with a bunch of styles but hard to get a tileset that actually looks nice but also can autotile. Not sure how other 2d games have larger "individual" tree sprites, I guess they are placed manually (which, idk if we are procedurally generating the rooms?)

![image](https://github.com/ErdrickBelmont/Buddy_Jam_2024_Team_4/assets/172531467/4670f649-2e2a-4ce1-872e-f5cdfb0119ba)
^ just a concept sketch

Tentatively settling on pixel art but had some issues getting lower res tiles to scale properly in godot 4 - didn't look into it too much, for now going w 128x128 tiles bc 64x64 looks pretty crappy. Need to fix the corners but going to work on the character to make sure the scale is ok

![image](https://github.com/ErdrickBelmont/Buddy_Jam_2024_Team_4/assets/172531467/276e2046-a258-4580-985e-0c3796305455)
^ example tilemap

---

other low priority things

- [ ] make tree tilemap transparent so you can set them on a different layer and have the character go behind the tops of trees
- [ ] alternate tiles for less obvious tiling
- [ ] actual ground tiles with grass

**Comment by vywn** [comment]
![image](https://github.com/ErdrickBelmont/Buddy_Jam_2024_Team_4/assets/172531467/bcbc1a28-1749-4166-8ce9-664918e4ff46)

wip 128px tileset used in example (wang) - will add the godot implementation to the repo in a bit

**Comment by ErdrickBelmont** [comment]
Looks nice V. So, we are going to have manually assembled maps with their connections scrambled every time there is a storm. There will also be small randomly toggled differences like maybe a wall in x location or sometimes not. Also, the alien trees will also be manually placed, but different # and location be toggled.

**Comment by vywn** [comment]
![tileset_forest-bg](https://github.com/ErdrickBelmont/Buddy_Jam_2024_Team_4/assets/172531467/6832133a-9844-4d2c-bca1-5e3c469ffb03)

fixed the corners

**Comment by vywn** [comment]
closing unless we need actual "doors"
